/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AddLazyImport = createFileRoute('/add')()
const IndexLazyImport = createFileRoute('/')()
const DeckDeckidIndexLazyImport = createFileRoute('/deck/$deck_id/')()
const DeckDeckidAddLazyImport = createFileRoute('/deck/$deck_id/add')()

// Create/Update Routes

const AddLazyRoute = AddLazyImport.update({
  path: '/add',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/add.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DeckDeckidIndexLazyRoute = DeckDeckidIndexLazyImport.update({
  path: '/deck/$deck_id/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/deck.$deck_id.index.lazy').then((d) => d.Route),
)

const DeckDeckidAddLazyRoute = DeckDeckidAddLazyImport.update({
  path: '/deck/$deck_id/add',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/deck.$deck_id.add.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddLazyImport
      parentRoute: typeof rootRoute
    }
    '/deck/$deck_id/add': {
      id: '/deck/$deck_id/add'
      path: '/deck/$deck_id/add'
      fullPath: '/deck/$deck_id/add'
      preLoaderRoute: typeof DeckDeckidAddLazyImport
      parentRoute: typeof rootRoute
    }
    '/deck/$deck_id/': {
      id: '/deck/$deck_id/'
      path: '/deck/$deck_id'
      fullPath: '/deck/$deck_id'
      preLoaderRoute: typeof DeckDeckidIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AddLazyRoute,
  DeckDeckidAddLazyRoute,
  DeckDeckidIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/add",
        "/deck/$deck_id/add",
        "/deck/$deck_id/"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/add": {
      "filePath": "add.lazy.jsx"
    },
    "/deck/$deck_id/add": {
      "filePath": "deck.$deck_id.add.lazy.jsx"
    },
    "/deck/$deck_id/": {
      "filePath": "deck.$deck_id.index.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
